---
micronaut:
  application:
    name: prometheus

---
micronaut:
  metrics:
    enabled: true

---
micronaut:
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
