---
micronaut:
  application:
    name: prometheus
  server:
    port: 8081
  metrics:
    enabled: true
    binders:
      jvm:
        enabled: false

---
micronaut:
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true

endpoints:
  prometheus:
    sensitive: false
